import { Loader2, ShieldCheck } from "lucide-react";

interface ProcessingPlaceholderProps {
  /** Variant of message shown to the user */
  variant?: "processing" | "watermark";
  /** Hide the textual label (use only shimmer + icon) */
  compact?: boolean;
}

/**
 * Elegant placeholder shown while the secure WebP variant (thumb/medium) is being
 * generated by the backend pipeline (Lambda + Sharp). NEVER falls back to the
 * original image — protecting unwatermarked assets is a hard security requirement.
 */
const ProcessingPlaceholder = ({
  variant = "processing",
  compact = false,
}: ProcessingPlaceholderProps) => {
  const label =
    variant === "watermark"
      ? "Gerando marca d'água..."
      : "Processando segurança e IA...";

  return (
    <div className="absolute inset-0 shimmer-skeleton flex flex-col items-center justify-center gap-2 text-muted-foreground">
      <div className="relative">
        <ShieldCheck className="w-6 h-6 opacity-40" />
        <Loader2 className="w-3.5 h-3.5 absolute -bottom-1 -right-1 animate-spin text-primary/70" />
      </div>
      {!compact && (
        <span className="text-[10px] font-medium text-center px-3 leading-tight max-w-[90%]">
          {label}
        </span>
      )}
    </div>
  );
};

export default ProcessingPlaceholder;